services:
  nexus:
    # image: klo2k/nexus3
    image: sonatype/nexus3
    ports:
      - 8081:8081
    networks:
      - ci_cd
    container_name: nexus

  sonarqube:
    image: sonarqube:10.4-community
    ports:
      - 9000:9000
    networks:
      - ci_cd
    container_name: sonar

  webserver:
    build: .
    image: tomcat:acada
    ports:
      - 8082:8080
    networks:
      - ci_cd
    container_name: tomcat

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8090:8080
      - 50000:50000
    networks:
      - ci_cd
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
volumes:
  jenkins-data:
    driver: local
networks:
  ci_cd:
